create unique index IDX_REFERENCEBOOKS_LOGBOOK_UNIQ_FORMAT on REFERENCEBOOKS_LOGBOOK (FORMAT);
create unique index IDX_REFERENCEBOOKS_LOGBOOK_UNIQ_CODE on REFERENCEBOOKS_LOGBOOK (CODE);
create unique index IDX_REFERENCEBOOKS_LOGBOOK_UNIQ_NAME on REFERENCEBOOKS_LOGBOOK (NAME);
