alter table REFERENCEBOOKS_EMPLOYEE add constraint FK_REFERENCEBOOKS_EMPLOYEE_ON_USER foreign key (USER_ID) references REFERENCEBOOKS_USER(ID);
create index IDX_REFERENCEBOOKS_EMPLOYEE_ON_USER on REFERENCEBOOKS_EMPLOYEE (USER_ID);
