alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE rename to CREATION_DATE__U85330 ^
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE__U85330 set null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT add column CREATION_DATE timestamp ^
update REFERENCEBOOKS_OUTGOING_DOCUMENT set CREATION_DATE = current_timestamp where CREATION_DATE is null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE set not null ;
