alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE rename to CREATION_DATE__U53505 ^
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE__U53505 set null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT add column CREATION_DATE date ^
update REFERENCEBOOKS_OUTGOING_DOCUMENT set CREATION_DATE = current_date where CREATION_DATE is null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column CREATION_DATE set not null ;
