alter table REFERENCEBOOKS_EMPLOYEE add constraint FK_REFERENCEBOOKS_EMPLOYEE_ON_USER foreign key (USER_ID) references REFERENCEBOOKS_USER(ID);
alter table REFERENCEBOOKS_EMPLOYEE add constraint FK_REFERENCEBOOKS_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references REFERENCEBOOKS_DEPARTMENT(ID);
create unique index IDX_REFERENCEBOOKS_EMPLOYEE_UNIQ_PHONE_NUMBER on REFERENCEBOOKS_EMPLOYEE (PHONE_NUMBER);
create unique index IDX_REFERENCEBOOKS_EMPLOYEE_UNIQ_EMAIL on REFERENCEBOOKS_EMPLOYEE (EMAIL);
create unique index IDX_REFERENCEBOOKS_EMPLOYEE_UNIQ_PERSONNEL_NUMBER on REFERENCEBOOKS_EMPLOYEE (PERSONNEL_NUMBER);
create unique index IDX_REFERENCEBOOKS_EMPLOYEE_UNIQ_USER_ID on REFERENCEBOOKS_EMPLOYEE (USER_ID);
create index IDX_REFERENCEBOOKS_EMPLOYEE_ON_USER on REFERENCEBOOKS_EMPLOYEE (USER_ID);
create index IDX_REFERENCEBOOKS_EMPLOYEE_ON_DEPARTMENT on REFERENCEBOOKS_EMPLOYEE (DEPARTMENT_ID);
create index IDX_REFERENCEBOOKS_EMPLOYEE on REFERENCEBOOKS_EMPLOYEE (LAST_NAME, PERSONNEL_NUMBER, DEPARTMENT_ID);
