alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column AUTHOR_ID rename to AUTHOR_ID__U44248 ^
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column AUTHOR_ID__U44248 set null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT drop constraint FK_REFERENCEBOOKS_OUTGOING_DOCUMENT_ON_AUTHOR ;
drop index IDX_REFERENCEBOOKS_OUTGOING_DOCUMENT_ON_AUTHOR ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT add column AUTHOR_ID varchar(36) ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT add column TOPIC varchar(255) ^
update REFERENCEBOOKS_OUTGOING_DOCUMENT set TOPIC = '' where TOPIC is null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column TOPIC set not null ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT add column RECIEPIENT varchar(255) ;
alter table REFERENCEBOOKS_OUTGOING_DOCUMENT alter column AUTHOR_ID set null ;
